# Generated by Django 5.0.6 on 2024-05-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marksheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marksheet',
            name='english_marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='hindi_marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='maths_marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='science_marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='socialstudy_marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='student_id',
            field=models.IntegerField(null=True),
        ),
    ]
